SET NAMES UTF8;

DROP TABLE IF EXISTS _USER;

CREATE TABLE `_USER` (
	`ID` VARCHAR(36) NOT NULL COLLATE 'utf8_unicode_ci',
	`EMAIL` VARCHAR(255) NOT NULL COLLATE 'utf8_unicode_ci',
	`PASSWORD_HASH` VARCHAR(60) NOT NULL COLLATE 'utf8_unicode_ci',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `EMAIL` (`EMAIL`)
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;

-- usuarios
INSERT INTO _USER (ID, EMAIL, PASSWORD_HASH) SELECT CONVERT_TO_UUID(ID), CONVERT(CAST(CONVERT(EMAIL USING LATIN1) AS BINARY) USING UTF8), PASSWORD FROM USER;

DROP TABLE IF EXISTS _FILE;

CREATE TABLE `_FILE` (
	`ID` VARCHAR(36) NOT NULL COLLATE 'utf8_unicode_ci',
	`SHA1_HASH` VARCHAR(40) NOT NULL COLLATE 'utf8_unicode_ci',
	`NAME` VARCHAR(256) NOT NULL COLLATE 'utf8_unicode_ci',
	`SIZE` BIGINT(20) UNSIGNED NOT NULL,
	`UPLOADED_BY` VARCHAR(36) NOT NULL COLLATE 'utf8_unicode_ci',
	`UPLOADED_ON` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `SHA1_HASH` (`SHA1_HASH`),
	INDEX `NAME` (`NAME`(255)),
	INDEX `SIZE` (`SIZE`),
	INDEX `UPLOADED_BY` (`UPLOADED_BY`),
	INDEX `UPLOADED_ON` (`UPLOADED_ON`)
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;

-- archivos
INSERT INTO _FILE (ID, SHA1_HASH, NAME, SIZE, UPLOADED_BY, UPLOADED_ON) SELECT CONVERT_TO_UUID(ID), SHA1_HASH, CONVERT(CAST(CONVERT(NAME USING LATIN1) AS BINARY) USING UTF8), SIZE, CONVERT_TO_UUID(USER_ID), UPLOADED FROM FILE ORDER BY UPLOADED;

DROP TABLE IF EXISTS _DOCUMENT;

CREATE TABLE `_DOCUMENT` (
	`ID` VARCHAR(36) NOT NULL COLLATE 'utf8_unicode_ci',
	`TITLE` VARCHAR(128) NOT NULL COLLATE 'utf8_unicode_ci',
	`DESCRIPTION` VARCHAR(4096) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`CREATED_BY` VARCHAR(36) NOT NULL COLLATE 'utf8_unicode_ci',
	`CREATED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	INDEX `CREATED_BY` (`CREATED_BY`, `TITLE`),
	INDEX `CREATED_ON` (`CREATED_ON`),
	INDEX `DESCRIPTION` (`DESCRIPTION`(255))
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;

-- documentos
INSERT INTO _DOCUMENT(ID, TITLE, DESCRIPTION, CREATED_BY, CREATED_ON) SELECT CONVERT_TO_UUID(ID), CONVERT(CAST(CONVERT(TITLE USING LATIN1) AS BINARY) USING UTF8), CONVERT(CAST(CONVERT(DESCRIPTION USING LATIN1) AS BINARY) USING UTF8), CONVERT_TO_UUID(USER_ID), CREATED FROM DOCUMENT ORDER BY CREATED;

DROP TABLE IF EXISTS _DOCUMENT_FILE;

CREATE TABLE `_DOCUMENT_FILE` (
	`DOCUMENT_ID` VARCHAR(36) NOT NULL COLLATE 'utf8_unicode_ci',
	`FILE_ID` VARCHAR(36) NOT NULL COLLATE 'utf8_unicode_ci',
	PRIMARY KEY (`DOCUMENT_ID`, `FILE_ID`)
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;

-- ficheros de documentos
INSERT INTO _DOCUMENT_FILE(DOCUMENT_ID, FILE_ID) SELECT CONVERT_TO_UUID(DOCUMENT_ID), CONVERT_TO_UUID(FILE_ID) FROM DOCUMENT_FILE;

DROP TABLE IF EXISTS _DOCUMENT_TAG;

CREATE TABLE `_DOCUMENT_TAG` (
	`DOCUMENT_ID` VARCHAR(36) NOT NULL COLLATE 'utf8_unicode_ci',
	`TAG` VARCHAR(32) NOT NULL COLLATE 'utf8_unicode_ci',
	PRIMARY KEY (`DOCUMENT_ID`, `TAG`)
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;

-- tags de documentos
INSERT INTO _DOCUMENT_TAG(DOCUMENT_ID, TAG) SELECT CONVERT_TO_UUID(DOCUMENT_ID), CONVERT(CAST(CONVERT(TAG USING LATIN1) AS BINARY) USING UTF8) FROM DOCUMENT_TAG;