SELECT
	CONCAT(
		"REPLACE INTO `USER` (id, email, password_hash) VALUES ('",
		CONVERT_TO_UUID(ID),
		"', '",
		CONVERT(CAST(CONVERT(EMAIL USING LATIN1) AS BINARY) USING UTF8),
		"', '",
		PASSWORD,
		"');"
	)
FROM USER;

SELECT
	CONCAT(
		"REPLACE INTO `FILE` (id, sha1_hash, name, size, uploaded_by_user_id, uploaded_on_timestamp) VALUES ('",
		CONVERT_TO_UUID(ID),
		"', '",
		SHA1_HASH,
		"', '",
		CONVERT(CAST(CONVERT(NAME USING LATIN1) AS BINARY) USING UTF8),
		"', ",
		SIZE,
		", '",
		CONVERT_TO_UUID(USER_ID),
		"', ",
		UNIX_TIMESTAMP(UPLOADED),
		");"
	)
FROM FILE
ORDER BY UPLOADED;

SELECT
	CONCAT(
		"REPLACE INTO `DOCUMENT` (id, title, description, created_by_user_id, created_on_timestamp) VALUES ('",
		CONVERT_TO_UUID(ID),
		"', '",
		CONVERT(CAST(CONVERT(TITLE USING LATIN1) AS BINARY) USING UTF8),
		"', '",
		CONVERT(CAST(CONVERT(COALESCE(DESCRIPTION, "") USING LATIN1) AS BINARY) USING UTF8),
	 	"', '",
	 	CONVERT_TO_UUID(USER_ID),
		"', ",
		UNIX_TIMESTAMP(CREATED),
		");"
	)
FROM DOCUMENT
ORDER BY CREATED;

SELECT
	CONCAT(
		"REPLACE INTO `DOCUMENT_FILE` (document_id, file_id) VALUES ('",
		CONVERT_TO_UUID(DOCUMENT_ID),
		"', '",
		CONVERT_TO_UUID(FILE_ID),
		"');"
	)
FROM DOCUMENT_FILE;


SELECT
	CONCAT(
		"REPLACE INTO `DOCUMENT_TAG` (document_id, tag) VALUES ('",
		CONVERT_TO_UUID(DOCUMENT_ID),
		"', '",
		CONVERT(CAST(CONVERT(TAG USING LATIN1) AS BINARY) USING UTF8),
		"');"
	)
FROM DOCUMENT_TAG;
