name: PHP Composer

on:
  push:
    branches: ["master"]
    paths:
      - "**/*.php"
      - "./phpslim-api/composer.json"
      - "./phpslim-api/composer.lock"
      - ".github/workflows/php.yml"
  pull_request:
    branches: ["master"]
    paths:
      - "**/*.php"
      - "./phpslim-api/composer.json"
      - "./phpslim-api/composer.lock"
      - ".github/workflows/php.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.2, 8.3]

    defaults:
      run:
        working-directory: ./phpslim-api

    steps:
      - uses: actions/checkout@v3

      # Install PHP 8.4
      - name: Set up PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Set up SQLite database
        run: php tools/install.php

      - name: Run test suite
        run: composer run-script test
